services:
  fex:
    image: stevenlafl/fex:steamcmd
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - ../../Steam:/home/fex/Steam
    stdin_open: true
    tty: true
    privileged: true
